import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { ConversionContext } from '../types';
import { GENERATOR_MARKER_SCAN_BYTES, isGeneratedHtml } from './output-targets';

/**
 * Throws when an output path holds a file this run must not replace.
 *
 * Only the debug HTML is guarded: a PDF at the output path is replaced, since
 * regenerating it is what the tool is for, but a `<stem>.html` without the
 * md2pdf generator marker was written by someone else (a hand-written
 * `index.html` next to `index.md`). `md2pdf.ts` calls this before the
 * conversion starts so nothing is rendered in vain, and `copyOutput` calls it
 * again right before writing.
 *
 * @param context - Mutable conversion state for the current source file.
 */
export function assertOutputReplaceable(context: ConversionContext): void {
  if (!context.options.html || !fs.existsSync(context.outputHtml)) {
    return;
  }

  if (!fs.statSync(context.outputHtml).isFile() || !isGeneratedHtml(readPrefix(context.outputHtml))) {
    throw new Error(
      `Refusing to overwrite ${context.outputHtml}: it was not generated by md2pdf. ` +
        'Move or delete it, or run without --debug.',
    );
  }
}

/**
 * Copies the generated PDF (and the debug HTML, when `--debug` is set) from
 * the temporary work directory to the target paths.
 *
 * Every output is first copied to a uniquely named file next to its target
 * and then swapped in with `renameSync`, so a failure at any point leaves the
 * previous file intact instead of truncated: `copyFileSync` opens and
 * truncates its destination before the copy can fail. A staged file that
 * could not be swapped in is removed again.
 *
 * @param context - Mutable conversion state for the current source file.
 */
export function copyOutput(context: ConversionContext): void {
  const outputs: { from: string; to: string }[] = [];

  if (!fs.existsSync(context.tempPdf)) {
    throw new Error(`PDF generation failed. Expected: ${context.tempPdf}`);
  }
  outputs.push({ from: context.tempPdf, to: context.outputPdf });

  if (context.options.html) {
    if (!fs.existsSync(context.tempHtml)) {
      throw new Error(`HTML generation failed. Expected: ${context.tempHtml}`);
    }
    outputs.push({ from: context.tempHtml, to: context.outputHtml });
  }

  assertOutputReplaceable(context);

  const staged: { file: string; to: string }[] = [];
  try {
    for (const { from, to } of outputs) {
      const file = stagingPath(to);
      staged.push({ file, to });
      fs.copyFileSync(from, file, fs.constants.COPYFILE_EXCL);
    }
    for (const { file, to } of staged) {
      fs.renameSync(file, to);
    }
  } finally {
    // After a successful rename the staged path no longer exists, so this
    // only removes what a failure left behind.
    staged.forEach(({ file }) => fs.rmSync(file, { force: true }));
  }
}

/**
 * Builds a unique temporary path in the target's own directory, so the final
 * `renameSync` never has to cross a filesystem boundary.
 *
 * @param target - Final output path.
 * @returns A path that does not collide with the target or another run.
 */
function stagingPath(target: string): string {
  const suffix = `${process.pid}-${crypto.randomBytes(4).toString('hex')}`;
  return path.join(path.dirname(target), `.${path.basename(target)}.${suffix}.tmp`);
}

/**
 * Reads the first {@link GENERATOR_MARKER_SCAN_BYTES} bytes of a file as UTF-8.
 *
 * @param file - File to read.
 * @returns The decoded prefix.
 */
function readPrefix(file: string): string {
  const fd = fs.openSync(file, 'r');
  try {
    const buffer = Buffer.alloc(GENERATOR_MARKER_SCAN_BYTES);
    const bytesRead = fs.readSync(fd, buffer, 0, buffer.length, 0);
    return buffer.toString('utf8', 0, bytesRead);
  } finally {
    fs.closeSync(fd);
  }
}
